### ISSUE TITLE
Reference proteome GFF

### ISSUE THREAD

**Issue by ireneortega** [MigleSur/GenAPI#14]
I would appreciate if you could add an option to use a proteome .gff file as reference in the gene_presence_absence_[name].txt file, so locustag are first included from that proteome. The same way as option -r in [get_homologues](http://eead-csic-compbio.github.io/get_homologues/manual/)

**Comment by MigleSur** [comment]
Dear Irene, 

Thank you for this suggestion. It would require adding a translation from amino acid sequences to nucleotide sequences as GenAPI is based on nucleotide sequences. It is impossible to do that unambiguously since several triplets can code for the same amino acid. Therefore, it is not planned to include such an option in GenAPI for now. Maybe in the future, GenAPI could be tested and ran on protein sequence instead of nucleotide. Then, both nucleotide and protein input files could be accepted.

**Comment by ireneortega** [comment]
Sorry, I didn't mean to perform amino acids alignment. I was referring to use one genome as "reference" from all the being analysed to construct the pangenome, so locustag in the gene_presence_absence_[name].txt file are first added from that "reference" genome.
